"""add index to perenual_id

Revision ID: 43f3e29aec05
Revises: 0d0fda5aa721
Create Date: 2026-05-06 16:34:00.416654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f3e29aec05'
down_revision: Union[str, Sequence[str], None] = '0d0fda5aa721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('plants_perenual_id_key'), 'plants', type_='unique')
    op.create_index(op.f('ix_plants_perenual_id'), 'plants', ['perenual_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plants_perenual_id'), table_name='plants')
    op.create_unique_constraint(op.f('plants_perenual_id_key'), 'plants', ['perenual_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
