"""add image_url to plants

Revision ID: 4a53f0475562
Revises: f84851adcad9
Create Date: 2026-04-24 19:20:11.285078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a53f0475562'
down_revision: Union[str, Sequence[str], None] = 'f84851adcad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'image_url')
    # ### end Alembic commands ###
