"""use JSONB

Revision ID: f84851adcad9
Revises: 
Create Date: 2026-04-24 10:09:36.225288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f84851adcad9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perenual_id', sa.Integer(), nullable=True),
    sa.Column('common_name', sa.String(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=True),
    sa.Column('other_name', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('hybrid', sa.Integer(), nullable=True),
    sa.Column('authority', sa.String(), nullable=True),
    sa.Column('subspecies', sa.String(), nullable=True),
    sa.Column('cultivar', sa.String(), nullable=True),
    sa.Column('variety', sa.String(), nullable=True),
    sa.Column('species_epithet', sa.String(), nullable=True),
    sa.Column('genus', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cycle', sa.String(), nullable=True),
    sa.Column('attracts', sa.String(), nullable=True),
    sa.Column('propagation', sa.String(), nullable=True),
    sa.Column('hardiness', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hardiness_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('watering', sa.String(), nullable=True),
    sa.Column('watering_general_benchmark', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sunlight', sa.String(), nullable=True),
    sa.Column('pruning_month', sa.String(), nullable=True),
    sa.Column('pruning_count', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seeds', sa.Boolean(), nullable=True),
    sa.Column('maintenance', sa.String(), nullable=True),
    sa.Column('care_guides', sa.String(), nullable=True),
    sa.Column('soil', sa.String(), nullable=True),
    sa.Column('growth_rate', sa.String(), nullable=True),
    sa.Column('drought_tolerant', sa.Boolean(), nullable=True),
    sa.Column('salt_tolerant', sa.Boolean(), nullable=True),
    sa.Column('thorny', sa.Boolean(), nullable=True),
    sa.Column('invasive', sa.Boolean(), nullable=True),
    sa.Column('tropical', sa.Boolean(), nullable=True),
    sa.Column('indoor', sa.Boolean(), nullable=True),
    sa.Column('care_level', sa.String(), nullable=True),
    sa.Column('pest_susceptibility', sa.String(), nullable=True),
    sa.Column('flowers', sa.Boolean(), nullable=True),
    sa.Column('flowering_season', sa.String(), nullable=True),
    sa.Column('cones', sa.Boolean(), nullable=True),
    sa.Column('fruits', sa.Boolean(), nullable=True),
    sa.Column('edible_fruit', sa.Boolean(), nullable=True),
    sa.Column('harvest_season', sa.String(), nullable=True),
    sa.Column('leaf', sa.Boolean(), nullable=True),
    sa.Column('edible_leaf', sa.Boolean(), nullable=True),
    sa.Column('cuisine', sa.Boolean(), nullable=True),
    sa.Column('medicinal', sa.Boolean(), nullable=True),
    sa.Column('poisonous_to_humans', sa.Boolean(), nullable=True),
    sa.Column('poisonous_to_pets', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_image', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('perenual_id')
    )
    op.create_index(op.f('ix_plants_id'), 'plants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plants_id'), table_name='plants')
    op.drop_table('plants')
    # ### end Alembic commands ###
